export interface WABlogPost {
	id?: string,
	public?: boolean,
	featured?: boolean,
	url?: string,
	title?: string,
	shortTitle?: string,
	date?: Date,
	thumbnail?: string,
	postPageThumbnail?: string,
	category?: string,
	tags?: string[],
	description?: string,
	body?: string,
	author?: string,
	contributors?: string[],
	downloadLink?: string,
	linkType?: string,
	starheads?: string[],
	screenshots?: string,
	video?: string,
	videoHost?: string
}

export const WABlogPostAttributeMap: any = {
	featured: 'Featured',
	title: 'Title',
	shortTitle: 'Short Title',
	date: 'Date',
	thumbnail: 'Thumbnail',
	postPageThumbnail: 'Post Page Thumbnail',
	category: 'Primary Category',
	tags: 'Categories',
	description: 'Brief Description',
	body: 'Post Body',
	author: 'Author',
	contributors: 'Contributors',
	downloadLink: 'Download Link',
	linkType: 'Link Type',
	starheads: 'Custom Star-head(s)',
	screenshots: 'Screenshots',
	video: 'Video'
}